#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

yarn check-types || 
(
  echo "Type checking failed. Please fix the errors and try again."
  false;
)

yarn check-format || 
(
  echo "Formatting failed. Please fix the errors and try again."
  false;
)

yarn lint --fix || 
(
  echo "Linting failed. Please fix the errors and try again."
  false;
)

yarn build || 
(
  echo "Build failed. Please fix the errors and try again."
  false;
)

git diff HEAD --quiet || 
(
  echo "You have uncommitted changes. Please commit them and try again."
  false;
)

echo "All checks passed. Committing..."
